### ISSUE TITLE
Fix: Description list tables need padding and code bgrd similar to regular tables.

### ISSUE THREAD

**Issue by stoobie** [starknet-io/starknet-docs-antora-ui#27]
The CSS styles for tables in doc.css have nice padding and the code within them appears with a nice background and rounded corners.

When using AsciiDco description lists, the HTML generated by Asciidoctor is a div with the class hdlist with a child table.

1. The padding of the hdlist table cells should match regular table cells, although the white frame around the table cells is not necessary.
2. The content of the cells in this table do not use p tags, and so the current styles for code in tables does not appear the same in hdlist tables. Need to adjust the styling to take this into account. 
     **IMPORTANT:** All changes should be made via CSS in the UI project, _not_ in the transformation from AsciiDoc to HTML.

**Comment by vibenedict** [comment]
Hi, i would like it to be assigned to me...

**Comment by stoobie** [comment]
@vibenedict I'd love for you to take this. Are you familiar with Antora?

**Comment by vibenedict** [comment]
@stoobie I know Antora but I haven't used it to any project before but it is something I can get familiar with in no time.

**Comment by stoobie** [comment]
Hey @vibenedict , OK, I assigned it to you. Be aware that the README needs some work.

Some tips I can give you to get started:
* The README is essentially the same README as the default Antora UI project. 
* The only changes I recall making are to specify the commands for previewing the UI project and building the bundle after you clone the project to your local environment. The commands I added work in my local environment.
* Feel free to update the readme while you're working to add any other helpful info that I didn't get around to.
* The files containing the AsciiDoc that appears in the browser when you preview the site are located in /preview-src. I generally just add a new section to index.adoc with what I want to test.
* You can use this AsciiDoc code to test the description list:
   ```
[horizontal,labelwidth="30",role=stripes-odd]
`address _token_`::
The address of the contract for the desired token.
`uint256 _amount_`::
The amount of the deposit.
`uint256 _l2Recipient_`::
The L2 address of the recipient.
```

**Comment by stoobie** [comment]
Hi @vibenedict Any update on this?

**Comment by vibenedict** [comment]
Hi @stoobie  almost done in a couple of days it will be ready...  I am facing some challenges fixing the  CSS at the moment.

**Comment by LandauRaz** [comment]
Closed due to inactivity.
