### ISSUE TITLE
feat: add codespell linter workflow for CI

### ISSUE THREAD

**Issue by xiaolou86** [starknet-io/starknet-docs-antora-ui#30]
Codespell linter tool is very important for code and system quality, especially for enhancing docs readability.

So I want to add codespell linter workflow for CI.

**Comment by xiaolou86** [comment]
Hello @stoobie , nice to see you here. Do you think it is need to add to this repo?

**Comment by stoobie** [comment]
@xiaolou86 I believe that you took care of this already in the starknet-docs repo, correct? If not, please reopen and give more details as to why this would be useful in this repo.
